language: c
dist: xenial
env:
  global:
    - TOOLS_DIR=$HOME/build_tools
    - GNAT_TAR_PATH=$TOOLS_DIR/gpl-2017-compiler.tar.gz
    - LINUX_GNAT_URL=http://mirrors.cdn.adacore.com/art/591c6d80c7a447af2deed1d7
    - DARWIN_GNAT_URL=http://mirrors.cdn.adacore.com/art/591c9045c7a447af2deed24e
os:
  - linux

cache:
  directories:
    - /home/travis/build_tools
    - /Users/travis/build_tools

install:
  # Check if the GNAT package is already available in the cache directory. If
  # not, download it.
  - >
      test -f $GNAT_TAR_PATH ||
      (mkdir -p $TOOLS_DIR &&
       if [ "$TRAVIS_OS_NAME" = "osx" ]; then
          wget $DARWIN_GNAT_URL -O $GNAT_TAR_PATH
       else
          wget $LINUX_GNAT_URL -O $GNAT_TAR_PATH
       fi
      )

  # Extract GNAT from its package
  - (mkdir -p ada-compiler && cd ada-compiler && tar --strip-components 1 -xzf $GNAT_TAR_PATH)

  # Grab lcov for coverage
  - sudo apt-get install -y lcov

  # Add GNAT to $PATH
  - export PATH=$PWD/ada-compiler/bin:$PATH

script:
  - gprbuild --version
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
